
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class Home extends javax.swing.JFrame {
    CodeEditor codeEditor;
    String path;
    String extension;

    

    /**
     * Creates new form Home
     */
     JFileChooser jFileChooser1;
    public Home() {
         jFileChooser1=new JFileChooser();
         jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);

        initComponents();
        simpleTitleBar1.init(this);
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpleTitleBar1 = new javaswingdev.SimpleTitleBar();
        leftPanel = new javax.swing.JPanel();
        profileBtn = new javax.swing.JLabel();
        dashboardBtn = new javax.swing.JLabel();
        settingsBtn = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        tabpane = new javax.swing.JTabbedPane();
        dashpage = new javax.swing.JPanel();
        javapane = new javax.swing.JPanel();
        javalogo = new javax.swing.JLabel();
        pythonpane = new javax.swing.JPanel();
        pythonlogo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        profpage = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        settingspage = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("La Lune");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        simpleTitleBar1.setBackground(new java.awt.Color(93, 0, 118));
        getContentPane().add(simpleTitleBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1400, -1));

        leftPanel.setBackground(new java.awt.Color(93, 0, 118));

        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profbutton.png"))); // NOI18N
        profileBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileBtnMouseExited(evt);
            }
        });

        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashbutton.png"))); // NOI18N
        dashboardBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseExited(evt);
            }
        });

        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/settingsbutton.png"))); // NOI18N
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsBtnMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/moon-small.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 144, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                        .addComponent(profileBtn)
                        .addContainerGap())
                    .addComponent(dashboardBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(settingsBtn, javax.swing.GroupLayout.Alignment.TRAILING)))
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(dashboardBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(profileBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(settingsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88)
                .addComponent(jLabel1)
                .addGap(101, 101, 101))
        );

        getContentPane().add(leftPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 300, 780));

        tabpane.setBackground(new java.awt.Color(255, 255, 255));

        javapane.setBackground(new java.awt.Color(93, 0, 118));
        javapane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        javapane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                javapaneMouseClicked(evt);
            }
        });

        javalogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/Java-Logo (1).png"))); // NOI18N
        javalogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout javapaneLayout = new javax.swing.GroupLayout(javapane);
        javapane.setLayout(javapaneLayout);
        javapaneLayout.setHorizontalGroup(
            javapaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, javapaneLayout.createSequentialGroup()
                .addContainerGap(149, Short.MAX_VALUE)
                .addComponent(javalogo)
                .addGap(129, 129, 129))
        );
        javapaneLayout.setVerticalGroup(
            javapaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, javapaneLayout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addComponent(javalogo)
                .addGap(92, 92, 92))
        );

        pythonpane.setBackground(new java.awt.Color(93, 0, 118));
        pythonpane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pythonpane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pythonpaneMouseClicked(evt);
            }
        });

        pythonlogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/pythonlogo (2).png"))); // NOI18N
        pythonlogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pythonpaneLayout = new javax.swing.GroupLayout(pythonpane);
        pythonpane.setLayout(pythonpaneLayout);
        pythonpaneLayout.setHorizontalGroup(
            pythonpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pythonpaneLayout.createSequentialGroup()
                .addContainerGap(154, Short.MAX_VALUE)
                .addComponent(pythonlogo)
                .addGap(134, 134, 134))
        );
        pythonpaneLayout.setVerticalGroup(
            pythonpaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pythonpaneLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(pythonlogo)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(93, 0, 118));
        jLabel2.setText("Choose language:");

        javax.swing.GroupLayout dashpageLayout = new javax.swing.GroupLayout(dashpage);
        dashpage.setLayout(dashpageLayout);
        dashpageLayout.setHorizontalGroup(
            dashpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dashpageLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(javapane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(pythonpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashpageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(398, 398, 398))
        );
        dashpageLayout.setVerticalGroup(
            dashpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dashpageLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel2)
                .addGap(69, 69, 69)
                .addGroup(dashpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pythonpane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(javapane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(243, Short.MAX_VALUE))
        );

        tabpane.addTab("tab1", dashpage);

        jPanel1.setBackground(new java.awt.Color(93, 0, 118));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 785, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout profpageLayout = new javax.swing.GroupLayout(profpage);
        profpage.setLayout(profpageLayout);
        profpageLayout.setHorizontalGroup(
            profpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profpageLayout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        profpageLayout.setVerticalGroup(
            profpageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, profpageLayout.createSequentialGroup()
                .addContainerGap(171, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        tabpane.addTab("tab3", profpage);

        jPanel2.setBackground(new java.awt.Color(93, 0, 118));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 824, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout settingspageLayout = new javax.swing.GroupLayout(settingspage);
        settingspage.setLayout(settingspageLayout);
        settingspageLayout.setHorizontalGroup(
            settingspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingspageLayout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );
        settingspageLayout.setVerticalGroup(
            settingspageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, settingspageLayout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        tabpane.addTab("tab2", settingspage);

        getContentPane().add(tabpane, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, -10, 1100, 810));

        setSize(new java.awt.Dimension(1400, 800));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseEntered
        // TODO add your handling code here:
        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashbutton_hv.png")));
    }//GEN-LAST:event_dashboardBtnMouseEntered

    private void dashboardBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseExited
        // TODO add your handling code here:
        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashbutton.png")));
    }//GEN-LAST:event_dashboardBtnMouseExited

    private void profileBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseEntered
        // TODO add your handling code here:
        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profbutton_hv.png")));
    }//GEN-LAST:event_profileBtnMouseEntered

    private void profileBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseExited
        // TODO add your handling code here:
        profileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/profbutton.png")));
    }//GEN-LAST:event_profileBtnMouseExited

    private void settingsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseEntered
        // TODO add your handling code here:
        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/settingsbutton_hv.png")));
    }//GEN-LAST:event_settingsBtnMouseEntered

    private void settingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseExited
        // TODO add your handling code here:
        settingsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/settingsbutton.png")));
    }//GEN-LAST:event_settingsBtnMouseExited

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
        // TODO add your handling code here:
        tabpane.setSelectedIndex(0);
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void profileBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileBtnMouseClicked
        // TODO add your handling code here:
        tabpane.setSelectedIndex(1);
    }//GEN-LAST:event_profileBtnMouseClicked

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        // TODO add your handling code here:
        tabpane.setSelectedIndex(2);
    }//GEN-LAST:event_settingsBtnMouseClicked

    private void javapaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_javapaneMouseClicked
         if(extension=="py"){
             JOptionPane.showMessageDialog(this,"Can only handle Python at the moment. Pls restart if you want to change language");
         } 
        if(path==null){
            if(jFileChooser1.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
                path=jFileChooser1.getSelectedFile().getAbsolutePath();
                 extension="java";
            }
           }
            codeEditor = CodeEditor.getJava(path);
            codeEditor.setVisible(true);
    }//GEN-LAST:event_javapaneMouseClicked

    private void pythonpaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pythonpaneMouseClicked
         if(extension=="java"){
             JOptionPane.showMessageDialog(this,"Can only handle Java at the moment. Pls restart if you want to change language");
         } 
        if(path==null){
            if(jFileChooser1.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
               
                path=jFileChooser1.getSelectedFile().getAbsolutePath();
                extension="py";
                
           
            }
        }
        
        codeEditor = CodeEditor.getPython(path);
        
         codeEditor.setVisible(true);
    }//GEN-LAST:event_pythonpaneMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dashboardBtn;
    private javax.swing.JPanel dashpage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel javalogo;
    private javax.swing.JPanel javapane;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JLabel profileBtn;
    private javax.swing.JPanel profpage;
    private javax.swing.JLabel pythonlogo;
    private javax.swing.JPanel pythonpane;
    private javax.swing.JLabel settingsBtn;
    private javax.swing.JPanel settingspage;
    private javaswingdev.SimpleTitleBar simpleTitleBar1;
    private javax.swing.JTabbedPane tabpane;
    // End of variables declaration//GEN-END:variables
}
